# Generated by Django 3.2.18 on 2023-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_noassistance_prompted_unprompted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noassistance',
            old_name='time_spent',
            new_name='time_spent_on_question',
        ),
        migrations.RenameField(
            model_name='prompted',
            old_name='time_spent',
            new_name='time_spent_on_question',
        ),
        migrations.RenameField(
            model_name='unprompted',
            old_name='time_spent',
            new_name='time_spent_on_question',
        ),
        migrations.AddField(
            model_name='noassistance',
            name='option_chosen',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='prompted',
            name='option_chosen',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='unprompted',
            name='option_chosen',
            field=models.JSONField(default=list),
        ),
    ]
