# Generated by Django 3.2.18 on 2023-11-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20231121_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('set_attempted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_attempted', models.IntegerField()),
                ('option_click_time', models.DurationField()),
                ('help_button_click_time', models.DurationField()),
                ('continue_button_click_time', models.DurationField()),
                ('time_spent_on_question', models.DurationField()),
                ('option_chosen', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.user')),
            ],
        ),
        migrations.DeleteModel(
            name='NoAssistance',
        ),
        migrations.DeleteModel(
            name='Prompted',
        ),
        migrations.DeleteModel(
            name='Unprompted',
        ),
    ]
