# Generated by Django 3.2.18 on 2023-11-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20231125_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoAssistanceAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Start', 'Start'), ('End', 'End'), ('Continue', 'Continue')], default='Null', max_length=10)),
                ('page', models.CharField(default='Null', max_length=200)),
                ('time', models.TimeField(default='00:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='PromptedAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Start', 'Start'), ('End', 'End'), ('Prompt', 'Prompt'), ('Continue', 'Continue')], default='Null', max_length=10)),
                ('page', models.CharField(default='Null', max_length=200)),
                ('time', models.TimeField(default='00:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='UnpromptedAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Start', 'Start'), ('End', 'End'), ('Prompt', 'Prompt'), ('Continue', 'Continue')], default='Null', max_length=10)),
                ('page', models.CharField(default='Null', max_length=200)),
                ('time', models.TimeField(default='00:00:00')),
            ],
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
    ]
