# Generated by Django 4.2.6 on 2023-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20231125_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='hint',
            new_name='actual_suggestion',
        ),
        migrations.AddField(
            model_name='question',
            name='misleading_suggestion',
            field=models.TextField(null=True),
        ),
    ]
