# Generated by Django 3.2.18 on 2023-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoAssistance',
            fields=[
                ('question_number', models.AutoField(primary_key=True, serialize=False)),
                ('option_click_time', models.DurationField()),
                ('help_button_click_time', models.DurationField()),
                ('continue_button_click_time', models.DurationField()),
                ('time_spent', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Prompted',
            fields=[
                ('question_number', models.AutoField(primary_key=True, serialize=False)),
                ('option_click_time', models.DurationField()),
                ('help_button_click_time', models.DurationField()),
                ('continue_button_click_time', models.DurationField()),
                ('time_spent', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Unprompted',
            fields=[
                ('question_number', models.AutoField(primary_key=True, serialize=False)),
                ('option_click_time', models.DurationField()),
                ('help_button_click_time', models.DurationField()),
                ('continue_button_click_time', models.DurationField()),
                ('time_spent', models.DurationField()),
            ],
        ),
    ]
